#!/bin/sh /etc/rc.common

START=21
STOP=89

USE_PROCD=1

start_service() {
	mkdir -p /var/log/suricata
	chown network /var/log/suricata

	procd_open_instance

	procd_set_param command /usr/bin/suricata
	procd_append_param command --user network
	procd_append_param command -q0
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_set_param term_timeout 15

	procd_close_instance
}
